services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  OpenAIBundle\AiFunction\:
    resource: '../../AiFunction/'
  OpenAIBundle\Command\:
    resource: '../../Command/'
  OpenAIBundle\Controller\:
    resource: '../../Controller/'
  OpenAIBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  OpenAIBundle\Procedure\:
    resource: '../../Procedure/'
  OpenAIBundle\Repository\:
    resource: '../../Repository/'
  OpenAIBundle\Service\:
    resource: '../../Service/'
